import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Canvas from "@/layout/Canvas";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App", //TODO
  description: "Generated by create next app", //TODO
};

//* This website is made to be mobile only.
//* Fix width as 360px.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex justify-center w-full h-svh bg-[#fff6e3]"}>
        <Canvas>
          {children}
        </Canvas>
      </body>
    </html>
  );
}
